Role/build infra
opentelekomcloud-infra/csm-ansible-roles pull request #10
Opened 2020-02-11 15:21 UTC by Polina-Gubina

2020-02-11 15:33 UTC, lego963 commented on build_infrastructure/molecule/default/files/infrastructure/settings.tf
> +  #auth_url  = "https://iam.eu-de.otc.t-systems.com:443/v3"
remove excess line

2020-02-13 08:23 UTC, outcatcher requested changes

2020-02-13 08:23 UTC, outcatcher commented on build_infrastructure/files/get_key.py
> +    os.chmod(get_key_from_s3(), RW_OWNER)
Please add newline

2020-02-13 08:23 UTC, outcatcher commented on build_infrastructure/molecule/default/files/infrastructure/variables.tf
> +
Please remove empty lines

2020-02-13 08:28 UTC, anton-sidelnikov commented on build_infrastructure/molecule/default/files/infrastructure/variables.tf
> +
remove endline

2020-02-13 08:29 UTC, lego963 commented on .gitignore
> +.terraform/
endline pls

2020-02-13 08:29 UTC, lego963 commented on build_infrastructure/defaults/main.yml
> +tf_variables:
remove if you don't use

2020-02-13 08:31 UTC, anton-sidelnikov commented on build_infrastructure/defaults/main.yml
> +infrastructure_dir: "infrastructure"
add terraform version 0.12.15

2020-02-13 08:31 UTC, lego963 commented on register_host/molecule/default/files/scenarios/infrastructure/infrastructure.tf
> +  password = var.password
format code

2020-02-13 08:32 UTC, lego963 commented on register_host/molecule/default/files/scenarios/infrastructure/infrastructure.tf
> +variable "password" {}
may you move variables out there?

2020-02-13 08:34 UTC, lego963 requested changes
fix singleline comments

2020-02-13 11:25 UTC, anton-sidelnikov submitted a review, later dismissed

2020-02-13 14:57 UTC, lego963 submitted a review, later dismissed

2020-02-13 15:29 UTC, outcatcher approved these changes

2020-02-13 15:36 UTC, merged