Check server version
opentelekomcloud-infra/csm-ansible-roles pull request #3
Opened 2019-12-30 07:37 UTC by lego963

If server is running it will be checked for version

2020-01-13 16:10 UTC, outcatcher requested changes

2020-01-13 16:10 UTC, outcatcher commented on too_simple_server/tasks/main.yml
> +  when: CURRENT_VERSION.stdout_lines[0] == LATEST_VERSION.stdout_lines[0] and CURRENT_VERSION.rc == 0
`CURRENT_VERSION.stdout_lines[0] == LATEST_VERSION.stdout_lines[0]`
Those two should be better saved as variables, like `current_version` and `latest_version`

2020-01-14 15:30 UTC, outcatcher commented on too_simple_server/tasks/main.yml
> +      when: server_state == 'absent' or force_new_download
We should restart server anyway

2020-01-17 13:01 UTC, anton-sidelnikov commented on too_simple_server/vars/main.yml
> +latest_version: "{{ LATEST_VERSION.stdout_lines[0] | default('0.4.3') }}"
default work here only if  default(some_variable, true)

2020-01-17 13:29 UTC, anton-sidelnikov approved these changes

2020-01-17 13:30 UTC, anton-sidelnikov requested changes
need fix

2020-01-20 10:56 UTC, Polina-Gubina approved these changes

2020-01-20 12:19 UTC, outcatcher approved these changes

2020-01-20 12:20 UTC, anton-sidelnikov approved these changes

2020-01-20 12:28 UTC, merged